{{- if and .Values.litestream.enabled (not .Values.litestream.s3Endpoint) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "keymeld.fullname" . }}-s3
  labels:
    {{- include "keymeld.labels" . | nindent 4 }}
type: Opaque
data:
  access-key-id: {{ .Values.litestream.s3AccessKeyId | default "" | b64enc | quote }}
  secret-access-key: {{ .Values.litestream.s3SecretAccessKey | default "" | b64enc | quote }}
{{- end }}
